### ISSUE TITLE
secrets的设置问题

### ISSUE THREAD

**Issue by RouJiANG-14** [natpacket/ssr_checkin#1]
大佬你好，请问是设置两个secrets么？
一个：EMAIL
一个：PASSWD
内容有什么格式要求么？
不是太懂代码，研究了一中午也没搞明白。

**Comment by natpacket** [comment]
你好，已经更新readme，请查看。不建议使用Github Actions。

**Comment by RouJiANG-14** [comment]
好的，感谢大佬，我会尝试使用云函数的！
